language: java
jdk:
  - openjdk10

script:
  - mvn clean test jacoco:report coveralls:report
  - mvn clean compile exec:java

before_deploy:
  - mvn javadoc:javadoc

deploy:
  - provider: script
    script: "cp .travis.settings.xml $HOME/.m2/settings.xml && mvn deploy"
    skip_cleanup: true
    on:
      tags: true
  - provider: pages
    local_dir: target/site/apidocs
    skip_cleanup: true
    github_token: $GITHUB_TOKEN
    on:
      tags: true
