language: java
jdk:
  - openjdk10

script:
  - mvn clean test jacoco:report coveralls:report

deploy:
  provider: script
  script: "cp .travis.settings.xml $HOME/.m2/settings.xml && mvn deploy"
  skip_cleanup: true
  on:
    tags: true
