//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/model_elm">http://java.sun.com/xml/model_elm</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.07.19 at 03:15:28 PM CDT 
//


package edu.phema.elm_to_omop.model_elm;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;
import javax.xml.namespace.QName;


/**
 * The Element type defines the abstract base type for all library elements in ELM.
 * 
 * <p>Java class for Element complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Element">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="annotation" type="{http://www.w3.org/2001/XMLSchema}anyType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="resultTypeSpecifier" type="{urn:hl7-org:elm:r1}TypeSpecifier" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="localId" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="locator" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="resultTypeName" type="{http://www.w3.org/2001/XMLSchema}QName" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Element", propOrder = {
    "annotation",
    "resultTypeSpecifier"
})
@XmlSeeAlso({
    Library.class,
    OperandDef.class,
    SortClause.class,
    CodeSystemDef.class,
    IncludeDef.class,
    TupleElementDefinition.class,
    TypeSpecifier.class,
    ValueSetDef.class,
    ParameterDef.class,
    ReturnClause.class,
    ExpressionDef.class,
    CaseItem.class,
    UsingDef.class,
    LetClause.class,
    SortByItem.class,
    CodeDef.class,
    AliasedQuerySource.class,
    ConceptDef.class,
    Expression.class
})
public abstract class Element {

    protected List<Object> annotation;
    protected TypeSpecifier resultTypeSpecifier;
    @XmlAttribute(name = "localId")
    protected String localId;
    @XmlAttribute(name = "locator")
    protected String locator;
    @XmlAttribute(name = "resultTypeName")
    protected QName resultTypeName;

    /**
     * Gets the value of the annotation property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the annotation property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAnnotation().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Object }
     * 
     * 
     */
    public List<Object> getAnnotation() {
        if (annotation == null) {
            annotation = new ArrayList<Object>();
        }
        return this.annotation;
    }

    /**
     * Gets the value of the resultTypeSpecifier property.
     * 
     * @return
     *     possible object is
     *     {@link TypeSpecifier }
     *     
     */
    public TypeSpecifier getResultTypeSpecifier() {
        return resultTypeSpecifier;
    }

    /**
     * Sets the value of the resultTypeSpecifier property.
     * 
     * @param value
     *     allowed object is
     *     {@link TypeSpecifier }
     *     
     */
    public void setResultTypeSpecifier(TypeSpecifier value) {
        this.resultTypeSpecifier = value;
    }

    /**
     * Gets the value of the localId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLocalId() {
        return localId;
    }

    /**
     * Sets the value of the localId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLocalId(String value) {
        this.localId = value;
    }

    /**
     * Gets the value of the locator property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLocator() {
        return locator;
    }

    /**
     * Sets the value of the locator property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLocator(String value) {
        this.locator = value;
    }

    /**
     * Gets the value of the resultTypeName property.
     * 
     * @return
     *     possible object is
     *     {@link QName }
     *     
     */
    public QName getResultTypeName() {
        return resultTypeName;
    }

    /**
     * Sets the value of the resultTypeName property.
     * 
     * @param value
     *     allowed object is
     *     {@link QName }
     *     
     */
    public void setResultTypeName(QName value) {
        this.resultTypeName = value;
    }

}
