//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/model_elm">http://java.sun.com/xml/model_elm</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.07.19 at 03:15:28 PM CDT 
//


package edu.phema.elm_to_omop.model_elm;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * The InValueSet operator returns true if the given code is in the given value set.
 * 			
 * Note that this operator explicitly requires a ValueSetRef as its valueset argument. This allows for both static analysis of the value set references within an artifact, as well as the implementation of valueset membership by the target environment as a service call to a terminology server, if desired.
 * 
 * <p>Java class for InValueSet complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="InValueSet">
 *   &lt;complexContent>
 *     &lt;extension base="{urn:hl7-org:elm:r1}Expression">
 *       &lt;sequence>
 *         &lt;element name="code" type="{urn:hl7-org:elm:r1}Expression"/>
 *         &lt;element name="valueset" type="{urn:hl7-org:elm:r1}ValueSetRef"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "InValueSet", propOrder = {
    "code",
    "valueset"
})
public class InValueSet
    extends Expression
{

    @XmlElement(required = true)
    protected Expression code;
    @XmlElement(required = true)
    protected ValueSetRef valueset;

    /**
     * Gets the value of the code property.
     * 
     * @return
     *     possible object is
     *     {@link Expression }
     *     
     */
    public Expression getCode() {
        return code;
    }

    /**
     * Sets the value of the code property.
     * 
     * @param value
     *     allowed object is
     *     {@link Expression }
     *     
     */
    public void setCode(Expression value) {
        this.code = value;
    }

    /**
     * Gets the value of the valueset property.
     * 
     * @return
     *     possible object is
     *     {@link ValueSetRef }
     *     
     */
    public ValueSetRef getValueset() {
        return valueset;
    }

    /**
     * Sets the value of the valueset property.
     * 
     * @param value
     *     allowed object is
     *     {@link ValueSetRef }
     *     
     */
    public void setValueset(ValueSetRef value) {
        this.valueset = value;
    }

}
