//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/model_elm">http://java.sun.com/xml/model_elm</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.07.19 at 03:15:28 PM CDT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "urn:hl7-org:elm:r1", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package edu.phema.elm_to_omop.model_elm;
