//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/model_elm">http://java.sun.com/xml/model_elm</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.07.19 at 03:15:28 PM CDT 
//


package edu.phema.elm_to_omop.model_elm;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * The Query operator represents a clause-based query. The result of the query is determined by the type of sources included, as well as the clauses used in the query.
 * 
 * <p>Java class for Query complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Query">
 *   &lt;complexContent>
 *     &lt;extension base="{urn:hl7-org:elm:r1}Expression">
 *       &lt;sequence>
 *         &lt;element name="source" type="{urn:hl7-org:elm:r1}AliasedQuerySource" maxOccurs="unbounded"/>
 *         &lt;element name="let" type="{urn:hl7-org:elm:r1}LetClause" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="relationship" type="{urn:hl7-org:elm:r1}RelationshipClause" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="where" type="{urn:hl7-org:elm:r1}Expression" minOccurs="0"/>
 *         &lt;element name="return" type="{urn:hl7-org:elm:r1}ReturnClause" minOccurs="0"/>
 *         &lt;element name="sort" type="{urn:hl7-org:elm:r1}SortClause" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Query", propOrder = {
    "source",
    "let",
    "relationship",
    "where",
    "_return",
    "sort"
})
public class Query
    extends Expression
{

    @XmlElement(required = true)
    protected List<AliasedQuerySource> source;
    protected List<LetClause> let;
    protected List<RelationshipClause> relationship;
    protected Expression where;
    @XmlElement(name = "return")
    protected ReturnClause _return;
    protected SortClause sort;

    /**
     * Gets the value of the source property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the source property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSource().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link AliasedQuerySource }
     * 
     * 
     */
    public List<AliasedQuerySource> getSource() {
        if (source == null) {
            source = new ArrayList<AliasedQuerySource>();
        }
        return this.source;
    }

    /**
     * Gets the value of the let property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the let property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getLet().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link LetClause }
     * 
     * 
     */
    public List<LetClause> getLet() {
        if (let == null) {
            let = new ArrayList<LetClause>();
        }
        return this.let;
    }

    /**
     * Gets the value of the relationship property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the relationship property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getRelationship().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link RelationshipClause }
     * 
     * 
     */
    public List<RelationshipClause> getRelationship() {
        if (relationship == null) {
            relationship = new ArrayList<RelationshipClause>();
        }
        return this.relationship;
    }

    /**
     * Gets the value of the where property.
     * 
     * @return
     *     possible object is
     *     {@link Expression }
     *     
     */
    public Expression getWhere() {
        return where;
    }

    /**
     * Sets the value of the where property.
     * 
     * @param value
     *     allowed object is
     *     {@link Expression }
     *     
     */
    public void setWhere(Expression value) {
        this.where = value;
    }

    /**
     * Gets the value of the return property.
     * 
     * @return
     *     possible object is
     *     {@link ReturnClause }
     *     
     */
    public ReturnClause getReturn() {
        return _return;
    }

    /**
     * Sets the value of the return property.
     * 
     * @param value
     *     allowed object is
     *     {@link ReturnClause }
     *     
     */
    public void setReturn(ReturnClause value) {
        this._return = value;
    }

    /**
     * Gets the value of the sort property.
     * 
     * @return
     *     possible object is
     *     {@link SortClause }
     *     
     */
    public SortClause getSort() {
        return sort;
    }

    /**
     * Sets the value of the sort property.
     * 
     * @param value
     *     allowed object is
     *     {@link SortClause }
     *     
     */
    public void setSort(SortClause value) {
        this.sort = value;
    }

}
