//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/model_elm">http://java.sun.com/xml/model_elm</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.07.19 at 03:15:28 PM CDT 
//


package edu.phema.elm_to_omop.model_elm;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;


/**
 * The UnaryExpression type defines the abstract base type for expressions that take a single argument.
 * 
 * <p>Java class for UnaryExpression complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="UnaryExpression">
 *   &lt;complexContent>
 *     &lt;extension base="{urn:hl7-org:elm:r1}Expression">
 *       &lt;sequence>
 *         &lt;element name="operand" type="{urn:hl7-org:elm:r1}Expression"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "UnaryExpression", propOrder = {
    "operand"
})
@XmlSeeAlso({
    Ceiling.class,
    ToDecimal.class,
    Distinct.class,
    IsFalse.class,
    TimeFrom.class,
    DateFrom.class,
    Predecessor.class,
    ToList.class,
    As.class,
    Abs.class,
    Upper.class,
    Convert.class,
    Length.class,
    Lower.class,
    Start.class,
    Not.class,
    End.class,
    DateTimeComponentFrom.class,
    Successor.class,
    IsTrue.class,
    Exists.class,
    IsNull.class,
    SingletonFrom.class,
    ToBoolean.class,
    ToInteger.class,
    Flatten.class,
    ToDateTime.class,
    Is.class,
    ToQuantity.class,
    Width.class,
    CalculateAge.class,
    ToString.class,
    TimezoneFrom.class,
    ToTime.class,
    PointFrom.class,
    Ln.class,
    ToConcept.class,
    Truncate.class,
    Collapse.class,
    Floor.class,
    Negate.class,
    Exp.class
})
public abstract class UnaryExpression
    extends Expression
{

    @XmlElement(required = true)
    protected Expression operand;

    /**
     * Gets the value of the operand property.
     * 
     * @return
     *     possible object is
     *     {@link Expression }
     *     
     */
    public Expression getOperand() {
        return operand;
    }

    /**
     * Sets the value of the operand property.
     * 
     * @param value
     *     allowed object is
     *     {@link Expression }
     *     
     */
    public void setOperand(Expression value) {
        this.operand = value;
    }

}
